### ISSUE TITLE
Not compiled to es5

### ISSUE THREAD

**Issue by mschipperheyn** [banterfm/graphql-crunch#18]
graphql-crunch doesn't follow the convention of publishing compiled libraries as es5. This can lead to a site appearing to funcion normally while bombing outright on Microsoft Edge. :-(

Please follow this convention. It prevents accidents.

**Comment by stevekrenzel** [comment]
This isn't a compiled library, so compiling to ES5 is non-trivial (it's not just a compile flag). Sorry if this doesn't work on your version of Microsoft Edge, but it should work fine on modern versions of Edge.

Closing this, but I'm open to PRs / someone maintaining Edge support if someone wants to run with that.
