### ISSUE TITLE
Dynamic require defined at line 5; not supported by Metro

### ISSUE THREAD

**Issue by AdamFoskit** [banterfm/graphql-crunch#25]
Trying to implement this wi react native and Apollo Client, but dynamically calling require does not work.

**Comment by JackHull** [comment]
Had the same problem - fixed by using an alternative import:

`
import uncrunch from 'graphql-crunch/src/v2/uncrunch'`

**Comment by stevekrenzel** [comment]
Fixed in https://github.com/banterfm/graphql-crunch/pull/21
