### ISSUE TITLE
Unexpected efficiency results with crunching

### ISSUE THREAD

**Issue by mschipperheyn** [banterfm/graphql-crunch#38]
Hi, I tried graphql-crunch on our largest json response: a newsfeed with posts. Common repeating elements are the posting user and associated groups.

Version 1 crunch
- Seems to extract the common elements properly
- The response file size seems actually larger than without crunching

Version 2 crunch
- It extracts common elements at a lower level when extracting at a higher level would be valid and more efficient. 
- E.g. a postUser contains a user and an optional impersonated group. Instead of referencing the post user as a whole, it only references the user and impersonated group, repeating the post user structure everywhere.

I do like the fact that v2 is much more readable.

I've attached example files.

[posts+crunch.zip](https://github.com/banterfm/graphql-crunch/files/5912882/posts%2Bcrunch.zip)

**Comment by stevekrenzel** [comment]
I believe this is operating as expected. The structural change in v2 was, in part, due to performance reasons. If two `postUser` entries are the *exact* same, they'll be deduped, but if they are different we'll get what you're seeing here.
