### ISSUE TITLE
Any plans to provide TypeScript declarations?

### ISSUE THREAD

**Issue by ordapad** [banterfm/graphql-crunch#39]

**Comment by kachkaev** [comment]
Looks like the latest version has `"types": "src/index.d.ts"` in `package.json` but no file itself:
https://unpkg.com/graphql-crunch@2.1.1/

**Comment by stevekrenzel** [comment]
I'd love to get TS support in here. I haven't had much time to iterate on `graphql-crunch` but will try to prioritize this.
